apiVersion: v2
name: openchoreo-secure-core
description: OpenChoreo Secure Core - Controller, API, Backstage with optional Cilium
type: application

# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"

home: https://github.com/openchoreo/openchoreo
icon: https://openchoreo.dev/img/openchoreo-logo.svg
sources:
  - https://github.com/openchoreo/openchoreo

keywords:
  - openchoreo
  - secure-core
  - controller
  - api
  - backstage

maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo
