# OpenChoreo Helm Values for Development Installation
# This file contains configuration for installing OpenChoreo components in a kind cluster

# Namespace configuration
namespace: openchoreo

# Controller Manager configuration
controllerManager:
  image:
    repository: openchoreo-controller
    tag: dev
    pullPolicy: IfNotPresent

# OpenChoreo API configuration
openchoreoApi:
  image:
    repository: openchoreo-api
    tag: dev
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - host: api.openchoreo.localhost
        paths:
          - path: /
            pathType: Prefix

# Backstage UI configuration
backstage:
  image:
    repository: openchoreo-ui
    tag: dev
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - host: openchoreo.localhost
        paths:
          - path: /
            pathType: Prefix